# SPDX-FileCopyrightText: 2023 The PFDL VS Code Extension Contributors
# SPDX-License-Identifier: MIT

name: Testing code visualization

on:
  pull_request:
    branches:
      - main
  push:
    paths:
      - 'client/src/**.ts'

permissions:
  contents: read

jobs:
  run-tests:
    name: Run unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install npm packages
        run: npm install
      - name: Run unit tests
        run: npm run test:ci
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: Unit test results
          path: ./junit.xml
      - name: Upload code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: Code coverage results
          path: coverage/cobertura-coverage.xml
