# SPDX-FileCopyrightText: The PFDL VS Code Extension Contributors
# SPDX-License-Identifier: CC0-1.0

name: Testing code visualization

on:
  pull_request:
    branches:
      - main
  push:
    paths:
      - 'client/src/**.ts'

permissions:
  contents: read

jobs:
  run-tests:
    name: Run unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '18'
      - name: Install npm packages
        run: npm install
      - name: Run unit tests
        run: npm run test:ci
      - name: Upload test results
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: Unit test results
          path: ./junit.xml
      - name: Upload code coverage results
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: Code coverage results
          path: coverage/cobertura-coverage.xml
